### ISSUE TITLE
Press enter instead/in addition to press button

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dmpg#11]
Is it possible to add content to the document by pressing enter instead or in addition to pressing the respective button (e.g. replace)?

I can imagine that many people will press enter after adding e.g. the project name out of habit, but this leads to a refresh of the site and then all content is gone.

**Comment by xiaoranzhou** [comment]
Fixed the "enter causes refresh bug". Now "enter" will submit input for a "text input", nothing will be done while pressing enter during the checkbox.
