### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dmpg#3]
For consitency it would be good if the colors used match the color schemes used by DataPLANT. 
Specifically I mean:
- The color of the boxes (e.g. general information, replace etc.)
- Color of "Example Project" etc. in the text: I would prefer another color than orange. Bright colors such as orange or yellow are not easy readable on white background for many people

**Comment by xiaoranzhou** [comment]
I have already used the base color of DataPLANT:
The color I use
![image](https://user-images.githubusercontent.com/29843510/151984801-c182a515-f338-48d3-9238-7bc89d30de68.png)
The color offered in https://github.com/nfdi4plants/Branding#colors
![image](https://user-images.githubusercontent.com/29843510/151984879-828536bc-a0d6-460b-a19d-2702451aecfc.png)

I can change the "after replacement words." color to background color
