### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/dmpg#6]
- It would be good that the warning location is highlighted (complete sentence/paragraph) instead of just having a message "warning location" at the end of the paragraph
- Is it possible to have the warning messages as a seperate section? For example: 6. Warnings? Then the users would not need to remove it manually if they want to change answers in previous steps after finishing all questions

**Comment by xiaoranzhou** [comment]
A red dot box was added to show the warnings.

We can also add a seperate section. The only problem is to store the solved issues. 
Firstly, the issues have the same tag. We need to save the content of the issue and then compare them afterwards. Considering the length of the content, there might be a performance issue.
Secondly, the issues might change when the answers are changed.
Thirdly, the issues might be different across different templates.
